### ISSUE TITLE
This sample is not working with APS connect

### ISSUE THREAD

**Issue by frostarun** [ingrammicro/fallball-connector#5]
Its failing at  **Install and configure Connector**

**Request** https://api-isv-oa.aps.odin.com/aps/2/applications/ returned code 500
**Error:** APS::Util::Exception

Message: Message: Error in application metadata: setting metadata with id 'appID' cannot be found
START OVER
 

ngROK output : 

POST /v1/app                   201 CREATED
POST /v1/app                   201 CREATED
GET  /v1/                      200 OK
GET  /v1/                      200 OK
GET  /v1/                      200 OK
GET  /v1/                      200 OK
GET  /v1/                      200 OK
GET  /v1/                      200 OK
GET  /v1/                      200 OK
GET  /v1/                      200 OK

config.yml :

debug: true
fallball_service_url: 'https://service-dot-fall-ball.appspot.com/v1/'
fallball_service_authorization_token: 1013f0b782709d635d02934f0090a4ffbb77cae9
oauth_key: fallball-connector-v1-60c1f2e0ee
oauth_secret: 1f6f3b9b3c9a406eb8e661c273f176dc
diskspace_resource: DISKSPACE
users_resource: USERS
gold_users_resource: GOLD_USERS
devices_resource: DEVICES
default_user_limit: 10
gold_user_limit: 15

**Comment by ToxicWar** [comment]
You should use fallball-connector from https://github.com/ingrammicro/fallball-connector/releases
Master fallball-connector v1.1.1, but https://app.aps.odin.com/ only v1.0.*

**Comment by frostarun** [comment]
I contacted support and they have done some changes in sampe and we managed to get a working connector. Thanks though.
