### ISSUE TITLE
/v1 => /connector

### ISSUE THREAD

**Issue by maxkuzkin** [ingrammicro/fallball-connector#6]
In the latest update, default path was changed to /connector, but README still shows /v1

**Comment by themaxbelov** [comment]
Thanks. Readme [updated](https://github.com/ingrammicro/fallball-connector/commit/7b1161843e3df05bfa03f03dad764ae396abad8a).

**Comment by ToxicWar** [comment]
New version released – https://github.com/ingrammicro/fallball-connector/releases/tag/v1.2.4
