### ISSUE TITLE
Config file not found on docker-compose up

### ISSUE THREAD

**Issue by danzar** [ingrammicro/fallball-connector#7]
I downloaded the zip, unzipped it, then processed to running the docker-compose up command.
I assume there was no setup (outside of the config.yml). Which I tried with and without changing to 
 config.yml to make sure I wasn't messing up the file somehow.

![screen shot 2017-10-05 at 2 24 44 pm](https://user-images.githubusercontent.com/2806049/31245759-5747845c-a9d9-11e7-9679-d2fc5ae63c3f.png)

**Comment by ToxicWar** [comment]
In docker-compose file we mount `config.yml` file in container, but with docker-machine it's impossible. See https://github.com/docker/machine/issues/179 for get more information.
With docker daemon on host you will not have such a problem
![image](https://user-images.githubusercontent.com/892060/31268372-9b977f62-aa84-11e7-8e22-2cd59bb10c7d.png)
